import data from "@/app/content-en";
import { poppinsClass } from "@/app/font";
import { CallTo, IconsSlider, MotionContainer, Statis } from "@/components";
import Image from "next/image";
import React from "react";
import { Marketing, contact, message, star, vision } from "../../../../public";
import Team from "@/components/Team";
import { animate } from "framer-motion";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

const timeline = [
  {
    title: "Move to Turkey",
    date: "14 January 2014",
    description:
      "Setting up ( Loyalty) headquarters in turkey in Istanbul in 2014 in the world trade center in Istanbul, which made the company stand out with its strategic location. Loyalty's team was made up of 4 people who were determined to implement the vision of the company",
  },
  {
    title: "Move to Turkey",
    date: "14 January 2014",
    description:
      "Setting up ( Loyalty) headquarters in turkey in Istanbul in 2014 in the world trade center in Istanbul, which made the company stand out with its strategic location. Loyalty's team was made up of 4 people who were determined to implement the vision of the company",
  },
  {
    title: "Move to Turkey",
    date: "14 January 2014",
    description:
      "Setting up ( Loyalty) headquarters in turkey in Istanbul in 2014 in the world trade center in Istanbul, which made the company stand out with its strategic location. Loyalty's team was made up of 4 people who were determined to implement the vision of the company",
  },
  {
    title: "Move to Turkey",
    date: "14 January 2014",
    description:
      "Setting up ( Loyalty) headquarters in turkey in Istanbul in 2014 in the world trade center in Istanbul, which made the company stand out with its strategic location. Loyalty's team was made up of 4 people who were determined to implement the vision of the company",
  },
];

const fadeInAnimationVArients = {
  initial: {
    opacity: 0,
    y: 100,
  },
  animate: {
    opacity: 1,
    y: 0,
  },
};

function Page() {
  return (
    <main className={`${poppinsClass}`}>
      <section className={`"flex  pb-5 py-[150px] `}>
        <div className="container md:justify-center md:items-center  flex flex-col ">
          <div className=" textContent md:text-center flex flex-col md:items-center">
            <MotionContainer
              initial={{ opacity: 0, y: 100 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1 }}
            >
              <h1 className=" text-[50px] max-w-[350px] md:text-[50px] md:max-w-[600px] font-bold text-primaryDark leading-[48px] md:*:text-center md:leading-[60px]">
                {data.heroAbout.title}
              </h1>
            </MotionContainer>
            <MotionContainer
              initial={{ opacity: 0, y: 100 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1.6 }}
            >
              <p className=" mt-[10px] max-w-[300px] md:max-w-[700px] text-[#686567] text-[16px]  font-medium leading-[27px]">
                {data.heroAbout.description}
              </p>
              <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
                {data.heroAbout.cta}
              </button>
            </MotionContainer>
          </div>
        </div>
      </section>
      <section>
        <div className="container about flex flex-col md:flex-row justify-center gap-3">
          <div className="embla__slide">
            <div className="embla__slide__number transition-colors">
              <div className=" img-container h-[60px] w-[60px] p-3 rounded-full bg-[#98E4E8]">
                <Image
                  src={message}
                  alt="img"
                  className="w-[100%] h-[100%] object-cover"
                  width={"100%"}
                  height={"100%"}
                />
              </div>
              <h3 className="mt-2 ">{data.heroAbout.items.message.title}</h3>
              <p className="mt-3 ">
                {data.heroAbout.items.message.description}
              </p>
            </div>
          </div>
          <div className="embla__slide">
            <div className="embla__slide__number transition-colors">
              <div className=" img-container h-[60px] w-[60px] p-3 rounded-full bg-[#98E4E8]">
                <Image
                  src={vision}
                  alt="img"
                  className="w-[100%] h-[100%] object-cover"
                  width={"100%"}
                  height={"100%"}
                />
              </div>
              <h3 className="mt-2 ">{data.heroAbout.items.vision.title}</h3>
              <p className="mt-3 ">{data.heroAbout.items.vision.description}</p>
            </div>
          </div>
          <div className="embla__slide">
            <div className="embla__slide__number transition-colors">
              <div className=" img-container h-[60px] w-[60px] p-3 rounded-full bg-[#98E4E8]">
                <Image
                  src={star}
                  alt="img"
                  className="w-[100%] h-[100%] object-cover"
                  width={"100%"}
                  height={"100%"}
                />
              </div>
              <h3 className="mt-2 ">{data.heroAbout.items.features.title}</h3>
              <p className="mt-3 ">
                {data.heroAbout.items.features.description}{" "}
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="py-10 my-5">
        <div className="container  flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">Who Are We ?</h5>
            </div>
            <h2 className="text-[32px] font-bold">Your Work Grows With Us</h2>
          </div>
          <p className="text-center max-w-[550px]">
            Established in 2013, our company specializes in branding, digital
            marketing, and programming. We expanded to Turkey in 2014, becoming
            an official entity under Turkish marketing laws in 2020.
            Additionally, we have branches in Dubai, UAE, and the USA.
          </p>
        </div>
        <div className="container my-[100px] md:my-[100px]">
          <div className="space-y-8 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-slate-300 before:to-transparent">
            {data.timeline.map((item, i) => (
              <div
                className="relative timeline-item flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group "
                key={i}
              >
                {/* <!-- Icon --> */}
                <div className="flex icon items-center justify-center w-10 h-10 rounded-full border border-white bg-slate-300 group-[.]:bg-emerald-500 text-slate-500 group-[.]:text-emerald-50 shadow shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2"></div>

                {/* <!-- Card --> */}
                <div className=" shadow-lg  card w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-white p-4 rounded-[10px] ">
                  <MotionContainer
                    initial={{ opacity: 0, y: 100 }}
                    animate={{ opacity: 1, y: 0 }}
                    whileInView={" animate"}
                  >
                    <div className="flex items-center justify-between space-x-2 mb-1">
                      <div className="font-bold text-slate-900 text-[20px]">
                        {item.title}
                      </div>
                      <time className=" font-Poppins font-medium text-[13px] text-secondary">
                        {item.date}
                      </time>
                    </div>
                    <div className="text-slate-500 mt-3">
                      {item.description}
                    </div>
                  </MotionContainer>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
      <section className=" py-10">
        <div className="container flex flex-col items-center justify-center ">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">{data.stats.smallTitle}</h5>
            </div>
            <h2 className="text-[32px] w-[354px] font-bold text-center">
              {data.stats.title}
            </h2>
          </div>
          <p className="text-center max-w-[550px]">{data.stats.description}</p>
        </div>
        <Statis object={data.stats} />
      </section>
      <section className=" bg-primaryDark py-2.5">
        <div className="container flex flex-col md:flex-row md:justify-between md:items-center">
          <div className=" flex flex-col py-4 ">
            <div className=" flex flex-col items-start">
              <h2 className="text-[32px] font-bold w-[350px] md:w-auto  leading-9 mt-3 text-white">
                {data.grow.title}
              </h2>
            </div>
            <p className=" text-white  w-[270px] md:w-[385px]  text-[16px] mt-4">
              {data.grow.description}
            </p>
            <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
              {data.grow.btn}
            </button>
          </div>
          <div className=" flex justify-end relative mt-4 md:mt-0 ">
            <Image
              src={contact}
              alt="homeHero"
              className=" md:w-[420px] mr-[-40px] "
              width={350}
              priority={true}
            />
          </div>
        </div>
      </section>
      <section className="py-5 pb-10 bg-primaryDark">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">{data.members.smallTitle}</h5>
            </div>
            <h2 className="text-[32px] font-bold text-white">
              {data.members.title}
            </h2>
          </div>
          <p className="text-center max-w-[550px] font-normal text-white">
            {data.members.description}
          </p>
          <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
            {data.members.btn}
          </button>
        </div>
        <Team members={data.members.items} />
      </section>
      <CallTo object={data} />
      <section className="py-10">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary ">{data.partners.smallTitle}</h5>
            </div>
            <h2 className="text-[27px] max-w-[550px] text-center font-bold">
              {data.partners.title}
            </h2>
          </div>
          <p className="text-center max-w-[550px] mt-3">
            {data.partners.description}
          </p>
        </div>
        <IconsSlider />
      </section>
    </main>
  );
}

export default Page;
