// "use client";

import dataAr from "@/app/content-ar";
import Image from "next/image";
// import { usePathname, useRouter } from "next/navigation";
import React from "react";
import { redirect } from "next/navigation";
import { cairoClass, poppinsClass } from "@/app/font";
import { MetaData } from "next";
import Head from "next/head";
import EmblaCarousel from "@/components/ui/EmblaCarousel";
import { EmblaCarousel2 } from "@/components/ui/EmblaCarousel2";
import Form from "@/components/Form";

// export const generateMetaData = ({ params }): Metadata => {
//   return {
//     title: params.projectTitle,
//   };
// };
export const metadata = {
  title: "project",
  description: "Generated by create next app",
};
// async function getStaticProps({ params }) {
//   console.log("Server-side log:", params.projectId);
//   return {
//     props: {
//       projectId: params.projectId,
//     },
//   };project.title

// }
const Page = ({ params }) => {
  let exist = true;
  metadata.title = dataAr.projects[params.projectId - 1].title;
  // metadata.title = decodeURIComponent(params.projectTitle).split("-").join(" ");

  console.log(params.projectTitle);
  console.log(decodeURIComponent(params.projectTitle));

  let projectObj = dataAr.projects[Number(params.projectId) - 1];
  const arrayOfStrings = decodeURIComponent(params.projectTitle).split("-");

  // console.log(arrayOfStrings);
  let Title = `Visual-Identity-Souq-alfurat`;
  // let Title = arrayOfStrings.join(" ");

  // console.log(Title);
  if (!projectObj || projectObj.url != params.projectTitle) {
    exist = false;
    redirect(`/en/not-found`);
  }
  const OPTIONS = { direction: "rtl" };
  return (
    <>
      <main className={` py-[100px] ${cairoClass}`}>
        <section className="pt-10 md:pt-20">
          <div className="container">
            {/* {!exist ? null : (
          // <div className=" ">
          //   product title :{params.projectId} {params.projectTitle}{" "}
          //   {`${projectObj.title}`}
          // </div>
          )} */}
            <div>
              <h1 className=" text-center leading-[118%] text-[50px] font-bold text-primaryDark">
                {projectObj.title}
              </h1>

              <div className="project-details my-10 flex justify-center gap-8 md:gap-[5rem]">
                <div className="client flex flex-col items-center justify-center">
                  <h4 className=" text-[#8A8A8A] font-medium text-[15px] text-center ">
                    العميل
                  </h4>
                  <h6 className=" text-primaryDark font-semibold text-center">
                    {projectObj.details.client}
                  </h6>
                </div>
                <div className="client flex flex-col items-center ">
                  <h4 className=" text-[#8A8A8A] font-medium text-[15px]">
                    الخدمات
                  </h4>
                  <h6 className=" text-primaryDark font-semibold text-center">
                    {projectObj.details.services}
                  </h6>
                </div>
                <div className="client flex flex-col items-center">
                  <h4 className=" text-[#8A8A8A] font-medium text-[15px]">
                    المدة الزمنية
                  </h4>
                  <h6 className=" text-primaryDark font-semibold text-center">
                    {projectObj.details.duration}
                  </h6>
                </div>
              </div>
            </div>
          </div>
          <div className="project-images flex justify-end  ">
            <EmblaCarousel2>
              {dataAr.projects[params.projectId - 1].details.images
                ? dataAr.projects[params.projectId - 1].details.images.map(
                    (project, i) => (
                      <div className=" mx-2 ms-[15px]  md:ms-[50px] " key={i}>
                        <div className="transition-colors  w-[350px] h-[250px] md:h-[535px] md:w-[800px] rounded-[10px] overflow-hidden">
                          <Image
                            src={project.img}
                            alt="img"
                            className="w-[100%] h-[100%] object-cover"
                            width={"100%"}
                            height={"100%"}
                          />
                        </div>
                      </div>
                    )
                  )
                : null}
              {}

              {/* <div className=" mx-2">
              <div className="transition-colors w-[350px] h-[250px] md:h-[535px] md:w-[800px] rounded-[10px] overflow-hidden">
                <Image
                  src={projectObj.img}
                  alt="img"
                  className="w-[100%] h-[100%] object-cover"
                  width={"100%"}
                  height={"100%"}
                />
              </div>
            </div>
            <div className=" mx-2">
              <div className="transition-colors w-[350px] h-[250px] md:h-[535px] md:w-[800px] rounded-[10px] overflow-hidden">
                <Image
                  src={projectObj.img}
                  alt="img"
                  className="w-[100%] h-[100%] object-cover"
                  width={"100%"}
                  height={"100%"}
                />
              </div>
            </div> */}
            </EmblaCarousel2>
          </div>
        </section>
        <section className=" bg-primaryDark py-[150px] mt-[-150px]">
          <div className="container">
            <div className="text-white my-6 flex flex-col md:flex-row md:justify-between">
              <h3 className=" text-[26px] font-bold">التحدي الذي يواجهنا</h3>
              <p className="mt-3 max-w-[600px]">
                لوريم إيبسوم دولور سيت أميت كونسيكتيتور. ليكتس ليو تينسيدنت
                إيبسوم ليبرو بلاسيرات. ليو ميتوس بورس تيمبور ليكتس. فيتاي
                أدبيسسينغ سيت كواس لوريت تيلوس مونتيس. إد إن فيفيرا سيد سينيكتوس
                أركو سيت.
                <br />
                <br />
                أدبيسسينغ سيت كواس لوريت تيلوس مونتيس. إد إن فيفيرا سيد سينيكتوس
                أركو سيت.
              </p>
            </div>
            <div className="text-white my-20 flex flex-col md:flex-row md:justify-between">
              <h3 className=" text-[26px] font-bold">الحل والنتيجة</h3>
              <p className="mt-3 max-w-[600px]">
                لوريم إيبسوم دولور سيت أميت كونسيكتيتور. ليكتس ليو تينسيدنت
                إيبسوم ليبرو بلاسيرات. ليو ميتوس بورس تيمبور ليكتس. فيتاي
                أدبيسسينغ سيت كواس لوريت تيلوس مونتيس. إد إن فيفيرا سيد سينيكتوس
                أركو سيت.
              </p>
            </div>
          </div>
          <div className="container">
            <div className="w-full h-[2px] bg-slate-500"></div>
          </div>
        </section>
        <section className=" bg-primaryDark pb-[100px]">
          <div className="container flex justify-center">
            <div className="w-[100%] md:w-[80%]">
              <Form />
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Page;
