// "use client";

import dataAr from "@/app/content-ar";
import Image from "next/image";
// import { usePathname, useRouter } from "next/navigation";
import React from "react";
import { redirect } from "next/navigation";
import { cairoClass, poppinsClass } from "@/app/font";
import { MetaData } from "next";
import Head from "next/head";

// export const generateMetaData = ({ params }): Metadata => {
//   return {
//     title: params.projectTitle,
//   };
// };
export const metadata = {
  title: "project",
  description: "Generated by create next app",
};
// async function getStaticProps({ params }) {
//   console.log("Server-side log:", params.projectId);
//   return {
//     props: {
//       projectId: params.projectId,
//     },
//   };project.title

// }
const Page = ({ params }) => {
  let exist = true;
  metadata.title = dataAr.projects[params.projectId - 1].title;
  // metadata.title = decodeURIComponent(params.projectTitle).split("-").join(" ");

  console.log(params.projectTitle);
  console.log(decodeURIComponent(params.projectTitle));

  let projectObj = dataAr.projects[Number(params.projectId) - 1];
  const arrayOfStrings = decodeURIComponent(params.projectTitle).split("-");

  // console.log(arrayOfStrings);
  let Title = `Visual-Identity-Souq-alfurat`;
  // let Title = arrayOfStrings.join(" ");

  // console.log(Title);
  if (!projectObj || projectObj.url != params.projectTitle) {
    exist = false;
    redirect(`/en/not-found`);
  }

  return (
    <>
      <main className={` py-[100px] ${cairoClass}`}>
        <div className="container">
          {!exist ? null : (
            <div className=" ">
              product title :{params.projectId}{" "}
              {decodeURIComponent(params.projectTitle)} {`${projectObj.title}`}
            </div>
          )}
          <h1 className=" text-center leading-[118%] text-[50px] font-bold text-primaryDark">
            {projectObj.title}
          </h1>
        </div>
      </main>
    </>
  );
};

export default Page;
