// "use client";

import data from "@/app/content-ar";
import Image from "next/image";
// import { usePathname, useRouter } from "next/navigation";
import React from "react";
import { redirect } from "next/navigation";
import { cairoClass, poppinsClass } from "@/app/font";
import { MetaData } from "next";
import Head from "next/head";
import EmblaCarousel from "@/components/ui/EmblaCarousel";
import Form from "@/components/Form";
import { EmblaCarousel2 } from "@/components/ui/EmblaCarousel2";

// export const generateMetaData = ({ params }): Metadata => {
//   return {
//     title: params.projectTitle,
//   };
// };
export const metadata = {
  title: "innovation",
  description: "Generated by create next app",
};
// async function getStaticProps({ params }) {
//   console.log("Server-side log:", params.projectId);
//   return {
//     props: {
//       projectId: params.projectId,
//     },
//   };project.title

// }
const Page = ({ params }) => {
  let exist = true;
  // metadata.title = `${params.title.split("-").join(" ")}`;

  console.log("Visual-Identity-Souq-alfurat");

  let projectObj = data.innovations[Number(params.id) - 1];
  // const arrayOfStrings = params.projectTitle.split("-");

  // // console.log(arrayOfStrings);
  // let Title = arrayOfStrings.join(" ");

  // console.log(Title);
  if (!projectObj || projectObj.url != params.innovTitle) {
    exist = false;
    redirect(`/en/not-found`);
  }

  return (
    <>
      <main className={` pt-[100px] ${cairoClass}`}>
        <section className="py-10 md:py-20  ">
          <div className="container md:flex">
            {/* {!exist ? null : (
            // <div className=" ">
            //   product title :{params.projectId} {params.projectTitle}{" "}
            //   {`${projectObj.title}`}
            // </div>
            )} */}
            <div className=" my-5 md:w-[50%] flex-1">
              <div>Read </div>
              <h1 className=" text-start leading-[118%] text-[50px] font-bold text-primaryDark">
                {projectObj.title}
              </h1>
              <p
                className="max-w-[400px]
              "
              >
                {projectObj.description}
              </p>
              <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
                Get Started
              </button>
            </div>
            <div className="project-images innovations  flex-1">
              <EmblaCarousel2>
                {data.innovations[params.id - 1].images
                  ? data.innovations[params.id - 1].images.map((innov, i) => (
                      <div className=" mx-2  md:ms-10  " key={i}>
                        <div className="transition-colors w-[350px] h-[300px] md:h-[438px] md:w-[420px] rounded-[10px] overflow-hidden">
                          <Image
                            src={innov.img}
                            alt="img"
                            className="w-[100%] h-[100%] object-cover"
                            width={"100%"}
                            height={"100%"}
                          />
                        </div>
                      </div>
                    ))
                  : null}
                {}

                {/* <div className=" mx-2">
                <div className="transition-colors w-[350px] h-[250px] md:h-[535px] md:w-[800px] rounded-[10px] overflow-hidden">
                  <Image
                    src={projectObj.img}
                    alt="img"
                    className="w-[100%] h-[100%] object-cover"
                    width={"100%"}
                    height={"100%"}
                  />
                </div>
              </div>
              <div className=" mx-2">
                <div className="transition-colors w-[350px] h-[250px] md:h-[535px] md:w-[800px] rounded-[10px] overflow-hidden">
                  <Image
                    src={projectObj.img}
                    alt="img"
                    className="w-[100%] h-[100%] object-cover"
                    width={"100%"}
                    height={"100%"}
                  />
                </div>
              </div> */}
              </EmblaCarousel2>
            </div>
          </div>
        </section>
        <section className=" bg-primaryDark py-[150px] pb-[100px] ">
          <div className="container">
            <div className="text-white my-6 flex flex-col md:flex-row md:justify-between">
              <h3 className=" text-[26px] font-bold">Our Challenge</h3>
              <p className="mt-3 max-w-[600px]">
                Lorem ipsum dolor sit amet consectetur. Lectus leo tincidunt
                ipsum libero placerat. Leo metus purus tempor lectus. Vitae
                adipiscing sit quis laoreet tellus montes. Id in viverra sed
                senectus arcu sit.
                <br />
                <br />
                adipiscing sit quis laoreet tellus montes. Id in viverra sed
                senectus arcu sit.
              </p>
            </div>
            <div className="text-white my-20 flex flex-col md:flex-row md:justify-between">
              <h3 className=" text-[26px] font-bold">Solution & Result</h3>
              <p className="mt-3 max-w-[600px]">
                Lorem ipsum dolor sit amet consectetur. Lectus leo tincidunt
                ipsum libero placerat. Leo metus purus tempor lectus. Vitae
                adipiscing sit quis laoreet tellus montes. Id in viverra sed
                senectus arcu sit.
              </p>
            </div>
          </div>
          <div className="container">
            <div className="w-full h-[2px] bg-slate-500"></div>
          </div>
        </section>
        <section className=" bg-primaryDark pb-[100px]">
          <div className="container flex justify-center">
            <div className="w-[100%] md:w-[80%]">
              <Form />
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Page;
