import React from "react";

export const metadata = {
  title: "Page in english",
  description: "Generated by create next app",
};

const page = () => {
  return <div>page</div>;
};

export default page;
