import data from "@/app/content-en";
import { poppinsClass } from "@/app/font";
import { CallTo } from "@/components";
import { poppins } from "@/components/Menubar";
import Image from "next/image";
import React from "react";
import { project, projectDe } from "../../../../public";
import Link from "next/link";

export const metadata = {
  title: "Page in english",
  description: "Generated by create next app",
};

const projects = [
  {
    title: "Visual Identity Souq alfurat ",
    tags: [
      {
        title: "Branding",
      },
      {
        title: "Design",
      },
    ],
    img: project,
  },
  {
    title: "Visual Identity Souq alfurat ",
    tags: [
      {
        title: "Branding",
      },
      {
        title: "Design",
      },
    ],
    img: project,
  },
  {
    title: "Visual Identity Souq alfurat ",
    tags: [
      {
        title: "Branding",
      },
      {
        title: "Design",
      },
    ],
    img: project,
  },
  {
    title: "Visual Identity Souq alfurat ",
    tags: [
      {
        title: "Branding",
      },
      {
        title: "Design",
      },
    ],
    img: project,
  },
  {
    title: "Visual Identity Souq alfurat ",
    tags: [
      {
        title: "Branding",
      },
      {
        title: "Design",
      },
    ],
    img: project,
  },
  {
    title: "Visual Identity Souq alfurat ",
    tags: [
      {
        title: "Branding",
      },
      {
        title: "Design",
      },
    ],
    img: project,
  },
];

const page = () => {
  console.log("hello");
  return (
    <main className={`${poppinsClass}`}>
      <section className={`"flex   pt-[150px] md:pt-[200px] pb-[100px] `}>
        <div className="container md:justify-center md:items-center  flex flex-col ">
          <div className=" textContent md:text-center flex flex-col md:items-center">
            <h1 className=" text-[50px] max-w-[550px] md:text-[50px] md:max-w-[800px] font-bold text-primaryDark leading-[55px] md:*:text-center md:leading-[60px]">
              With Programming{" "}
              <span className=" text-secondary">To Give You </span>The Best
              Results
            </h1>
            <p className=" mt-[10px] max-w-[300px] md:max-w-[700px] text-[#686567] text-[16px] font-Roboto font-medium leading-[27px]">
              {data.heroAbout.description}
            </p>
            <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
              {data.heroAbout.cta}
            </button>
          </div>
        </div>
      </section>
      <section className="py-10 bg-[#191C1D]">
        <div className=" flex flex-col items-center">
          <div className="flex items-center mb-[-5px]">
            <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
            <h5 className=" text-secondary">Our projects</h5>
          </div>
          <h2 className="text-[32px] font-bold text-white">
            See Our Latest Projects
          </h2>
        </div>
        <div className=" container">
          <div className="projects my-10">
            <div className="projects-btn">
              <div className="projects-container flex flex-col items-center md:flex-row  justify-center gap-5 flex-wrap">
                {data.projects.map((project, i) => (
                  <div
                    className="project rounded-[10px] overflow-hidden w-[333px] relative"
                    key={i}
                  >
                    <Image
                      src={project.img}
                      alt={project.title}
                      className=" hover:scale-110 transition-all"
                    />
                    <div className="absolute bottom-[0px] px-3 translate-y-[-20%]">
                      <Link
                        href={`/en/projects/${i + 1}/${project.title
                          .split(" ")
                          .join("-")}`}
                      >
                        <h2 className=" text-white font-bold text-[28px] hover:text-secondary transition-colors cursor-pointer">
                          {project.title}
                        </h2>
                      </Link>
                      <div className="tags mt-4 flex gap-2">
                        {project.tags.map((tag, i) => (
                          <div
                            className=" bg-white w-fit py-1 px-4 rounded-[5px] text-[14px] flex items-center font-semibold "
                            key={i}
                          >
                            {tag.title}
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
        <div className="mt-20">
          <CallTo object={data} />
        </div>
      </section>
    </main>
  );
};

export default page;
