import { Poppins, Roboto } from "next/font/google";
import { Cairo } from "next/font/google";
import Image from "next/image";


import BounceBall from "@/components/BounceBall";
import { Marketing, homeHero } from "../../../../public";

import Services from "@/components/Services";
import StrategyAr from "@/components/StrategyAr";

const cairo = Cairo({
  subsets: ["arabic"],

  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});
const roboto = Roboto({
  family: "Roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const poppins = Poppins({
  family: "Poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const sliderImageUrl = [
  //First image url
  {
    title: "التسويق الرقمي",
    imgDark: Marketing,
    description:
      "هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم ",
  },
  {
    title: "حلول برمجية",
    imgDark: Marketing,
    description:
      "هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم ",
  },
  //Second image url
  {
    title: "تصميم",
    imgDark: Marketing,
    description:
      "هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم ",
  },
  //Third image url
  {
    title: "تطبيق الهاتف المحمول",
    imgDark: Marketing,
    description:
      "هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم ",
  },
];

export const metadata = {
  title: "الصفحة بالعربية",
  description: "Generated by create next app",
};

export default function Home() {
  // const locale = useLocale();
  // console.log("Current locale:", locale); // Out
  return (
    <main dir="rtl" className={` ${cairo.className}`}>
      <section className={`"flex  py-5 pt-[100px]  `}>
        <div className="container md:justify-between md:items-center  flex flex-col md:flex-row">
          <div className=" textContent">
            <h1 className=" font-black text-[40px] max-w-[350px] md:text-[50px] md:max-w-[500px]  text-primaryDark leading-[48px] md:leading-[60px]">
              بناء المنتج الرقمي والعلامة التجارية والخبرة
            </h1>
            <p className="  mt-[10px] max-w-[300px] md:max-w-[400px] text-[#686567] text-[16px]  font-medium">
              نحن وكالة تسويق ووكالة رقمية، نقدم الكثير من الخدمات نحن وكالة
              تسويق ووكالة رقمية، نقدم الكثير من الخدمات
            </p>
            <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
              Get Started
            </button>
          </div>
          <div className=" flex justify-end relative">
            <BounceBall />
            <Image
              src={homeHero}
              alt="homeHero"
              className=" w-[350px] md:w-[420px]  scale-x-[-1] "
              width={350}
              priority={true}
            />
          </div>
        </div>
      </section>
      <section className="py-5">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-start">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[25px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">ماذا نقدم ؟</h5>
            </div>
            <h2 className="text-[32px] font-bold">خدماتنا</h2>
          </div>
          <p className="text-center max-w-[550px]">
            هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم
            هذا مجرد محتوى مزيف لملء التصميم
          </p>
        </div>
        <Services object={sliderImageUrl} />
      </section>
      <section className="py-5 bg-primaryDark">
        <StrategyAr />
      </section>
    </main>
  );
}
