import Image from "next/image";

import dataAr from "@/app/content-ar";
import BounceBall from "@/components/BounceBall";
import { contact, homeHero } from "../../../../public";

// import  from "@/components/Services";
import StrategyAr from "@/components/StrategyAr";
import Features from "@/components/Features";

import Team from "@/components/Team";
import Clients from "@/components/Clients";
import { CallTo, IconsSlider, Statis, Services } from "@/components";
import { cairoClass } from "@/app/font";

export const metadata = {
  title: "الصفحة بالعربية",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main dir="rtl" className={` ${cairoClass}`}>
      <section className={`"flex  py-5 pt-[100px]  `}>
        <div className="container md:justify-between md:items-center  flex flex-col md:flex-row">
          <div className=" textContent">
            <h1 className=" font-black text-[40px] max-w-[350px] md:text-[50px] md:max-w-[500px]  text-primaryDark leading-[48px] md:leading-[60px]">
              بناء المنتج الرقمي والعلامة التجارية والخبرة
            </h1>
            <p className="  mt-[10px] max-w-[300px] md:max-w-[400px] text-[#686567] text-[16px]  font-medium">
              نحن وكالة تسويق ووكالة رقمية، نقدم الكثير من الخدمات نحن وكالة
              تسويق ووكالة رقمية، نقدم الكثير من الخدمات
            </p>
            <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
              تواصل معنا
            </button>
          </div>
          <div className=" flex justify-end relative">
            <BounceBall />
            <Image
              src={homeHero}
              alt="homeHero"
              className=" w-[350px] md:w-[420px]  scale-x-[-1] "
              width={350}
              priority={true}
            />
          </div>
        </div>
      </section>
      <section className="py-5">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-start">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[25px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">{dataAr.services.smallTitle}</h5>
            </div>
            <h2 className="text-[32px] font-bold">{dataAr.services.title}</h2>
          </div>
          <p className="text-center max-w-[550px]">
            {dataAr.services.description}
          </p>
        </div>
        <Services object={dataAr.services.servicesItems} options={"rtl"} />
      </section>
      <section className="py-5 bg-primaryDark">
        <StrategyAr />

        <div className="container flex flex-col md:flex-row md:justify-between md:items-center">
          <div className=" flex flex-col py-4 ">
            <div className=" flex flex-col items-start">
              <h2 className="text-[32px] font-bold w-[300px] md:w-auto  leading-9 mt-3 text-white">
                {dataAr.grow.title}{" "}
              </h2>
            </div>
            <p className=" text-white  w-[270px] md:w-[385px]  text-[16px] mt-4">
              {dataAr.grow.description}
            </p>
            <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
              {dataAr.grow.btn}
            </button>
          </div>
          <div className=" flex justify-end relative mt-4 md:mt-0 ">
            <Image
              src={contact}
              alt="homeHero"
              className=" md:w-[420px] ml-[-40px] scale-x-[-1] "
              width={350}
              priority={true}
            />
          </div>
        </div>
      </section>
      <section className="py-5">
        <Features object={dataAr.features} />
      </section>
      <section className=" py-10">
        <div className="container flex flex-col items-center justify-center ">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">{dataAr.stats.smallTitle}</h5>
            </div>
            <h2 className="text-[32px] w-[354px] font-bold text-center">
              {dataAr.stats.title}
            </h2>
          </div>
          <p className="text-center max-w-[550px]">
            {dataAr.stats.description}
          </p>
        </div>
        <Statis object={dataAr.stats} />
      </section>
      <section className="py-10">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary ">{dataAr.clients.smallTitle}</h5>
            </div>
            <h2 className="text-[32px] max-w-[300px] text-center font-bold">
              {dataAr.clients.title}
            </h2>
          </div>
          <p className="text-center max-w-[550px]">
            {dataAr.clients.description}{" "}
          </p>
        </div>
        <Clients object={dataAr.clients.items} />
      </section>
      <section className="py-10 bg-primaryDark">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">{dataAr.members.smallTitle}</h5>
            </div>
            <h2 className="text-[32px] font-bold text-white">
              {dataAr.members.title}
            </h2>
          </div>
          <p className="text-center max-w-[550px] font-normal text-white mt-3">
            {dataAr.members.description}
          </p>
          <button className="w-fit text-primary text-[14px] font-medium mt-5  bg-secondary rounded-full px-9 py-3">
            {dataAr.members.btn}{" "}
          </button>
        </div>
        <Team members={dataAr.members.items} />
      </section>

      <CallTo object={dataAr} />
      <section className="py-10">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary ">{dataAr.partners.smallTitle}</h5>
            </div>
            <h2 className="text-[27px] max-w-[550px] text-center font-bold">
              {dataAr.partners.title}
            </h2>
          </div>
          <p className="text-center max-w-[550px] mt-3">
            {dataAr.partners.description}
          </p>
        </div>
        <IconsSlider />
      </section>
    </main>
  );
}
