import { Poppins, Roboto } from "next/font/google";
import { Cairo } from "next/font/google";
import Image from "next/image";


import BounceBall from "@/components/BounceBall";
import {
  Marketing,
  contact,
  homeHero,
  memberTeam,
  strategy,
  support,
} from "../../../../public";

import Services from "@/components/Services";
import StrategyAr from "@/components/StrategyAr";
import Features from "@/components/Features";
import FooterAr from "@/components/FooterAr";
import Team from "@/components/Team";
import Clients from "@/components/Clients";

const features = {
  smallTitle: "مميزاتنا",
  title: "أفضل شركة في إسطنبول",
  description: `نحن الأفضل لأننا نمزج بين التسويق والبرمجة والتصميم المعقد معًا للحصول على أفضل النتائج. بعد أن نقوم بتطوير هوية علامتك التجارية الخاصة، 
  نساعدك على تنمية علامتك التجارية من خلال إعداد الحملات التسويقية عبر وسائل التواصل الاجتماعي ومحركات البحث.
 
بالتوازي نقوم بتطوير موقع الويب الخاص بك بالإضافة إلى التطبيقات والبرامج الخاصة بعلاقات العملاء والمبيعات والمحاسبة.`,
  items: [
    {
      icon: strategy,
      title: "الخطط والمشورة",
    },
    {
      icon: support,
      title: "دعم على مدار الساعة",
    },
    {
      icon: strategy,
      title: "افكار جديدة",
    },
  ],
};

const cairo = Cairo({
  subsets: ["arabic"],

  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});
const roboto = Roboto({
  family: "Roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const poppins = Poppins({
  family: "Poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const sliderImageUrl = [
  //First image url
  {
    title: "التسويق الرقمي",
    imgDark: Marketing,
    description:
      "هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم ",
  },
  {
    title: "حلول برمجية",
    imgDark: Marketing,
    description:
      "هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم ",
  },
  //Second image url
  {
    title: "تصميم",
    imgDark: Marketing,
    description:
      "هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم ",
  },
  //Third image url
  {
    title: "تطبيق الهاتف المحمول",
    imgDark: Marketing,
    description:
      "هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم ",
  },
];

const members = [
  {
    name: "جنيد العمر",
    role: "المؤسس",
    img: memberTeam,
  },
  {
    name: "هشام حجازي",
    role: "مطور ويب",
    img: memberTeam,
  },
  {
    name: "سفيان خلف الله",
    role: "مطور ويب",
    img: memberTeam,
  },
  {
    name: "ياسين باسو",
    role: "مطور ويب",
    img: memberTeam,
  },
  {
    name: "سفيان خلف الله",
    role: "مطور ويب",
    img: memberTeam,
  },
];

export const metadata = {
  title: "الصفحة بالعربية",
  description: "Generated by create next app",
};

export default function Home() {
  // const locale = useLocale();
  // console.log("Current locale:", locale); // Out
  return (
    <main dir="rtl" className={` ${cairo.className}`}>
      <section className={`"flex  py-5 pt-[100px]  `}>
        <div className="container md:justify-between md:items-center  flex flex-col md:flex-row">
          <div className=" textContent">
            <h1 className=" font-black text-[40px] max-w-[350px] md:text-[50px] md:max-w-[500px]  text-primaryDark leading-[48px] md:leading-[60px]">
              بناء المنتج الرقمي والعلامة التجارية والخبرة
            </h1>
            <p className="  mt-[10px] max-w-[300px] md:max-w-[400px] text-[#686567] text-[16px]  font-medium">
              نحن وكالة تسويق ووكالة رقمية، نقدم الكثير من الخدمات نحن وكالة
              تسويق ووكالة رقمية، نقدم الكثير من الخدمات
            </p>
            <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
              Get Started
            </button>
          </div>
          <div className=" flex justify-end relative">
            <BounceBall />
            <Image
              src={homeHero}
              alt="homeHero"
              className=" w-[350px] md:w-[420px]  scale-x-[-1] "
              width={350}
              priority={true}
            />
          </div>
        </div>
      </section>
      <section className="py-5">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-start">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[25px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">ماذا نقدم ؟</h5>
            </div>
            <h2 className="text-[32px] font-bold">خدماتنا</h2>
          </div>
          <p className="text-center max-w-[550px]">
            هذا مجرد محتوى مزيف لملء التصميم هذا مجرد محتوى مزيف لملء التصميم
            هذا مجرد محتوى مزيف لملء التصميم
          </p>
        </div>
        <Services object={sliderImageUrl} />
      </section>
      <section className="py-5 bg-primaryDark">
        <StrategyAr />

        <div className="container flex flex-col md:flex-row md:justify-between md:items-center">
          <div className=" flex flex-col py-4 ">
            <div className=" flex flex-col items-start">
              {/* <div className="flex items-center mb-[-5px]">
                <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
                <h5 className=" text-white">Workflow</h5>
              </div> */}
              <h2 className="text-[32px] font-bold w-[300px] md:w-auto  leading-9 mt-3 text-white">
                قم بتنمية أعمالك اليوم
              </h2>
            </div>
            <p className=" text-white  w-[270px] md:w-[385px]  text-[16px] mt-4">
              بدءًا من تحسين هوية علامتك التجارية وتشغيل الحملات وحتى تعزيز
              تواجدك الرقمي، فإننا نقوم بكل ذلك
            </p>
            <button className="w-fit text-primary text-[14px] font-medium mt-4  bg-secondary rounded-full px-9 py-3">
              تواصل معنا
            </button>
          </div>
          <div className=" flex justify-end relative mt-4 md:mt-0 ">
            <Image
              src={contact}
              alt="homeHero"
              className=" md:w-[420px] ml-[-40px] scale-x-[-1] "
              width={350}
              priority={true}
            />
          </div>
        </div>
      </section>
      <section className="py-5">
        <Features object={features} />
      </section>
      <section className="py-5 bg-primaryDark">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary">فريقنا</h5>
            </div>
            <h2 className="text-[32px] font-bold text-white">
              تعرف على فريقنا{" "}
            </h2>
          </div>
          <p className="text-center max-w-[550px] font-normal text-white mt-3">
            بدءًا من تحسين هوية علامتك التجارية وتشغيل الحملات وحتى تعزيز تواجدك
            الرقمي، فإننا نقوم بكل ذلك
          </p>
          <button className="w-fit text-primary text-[14px] font-medium mt-5  bg-secondary rounded-full px-9 py-3">
            انضم إلى فريقنا
          </button>
        </div>
        <Team members={members} />
      </section>
      <section className="py-10">
        <div className="container flex flex-col items-center justify-center my-10">
          <div className=" flex flex-col items-center">
            <div className="flex items-center mb-[-5px]">
              <div className="w-[60px] h-[2px] bg-secondary mr-1"></div>
              <h5 className=" text-secondary ">عملائنا</h5>
            </div>
            <h2 className="text-[32px] max-w-[300px] text-center font-bold">
              ماذا يقول عملاؤنا؟{" "}
            </h2>
          </div>
          <p className="text-center max-w-[550px]">
            وكما قلنا من قبل نشجعك على الغوص قبل اليقين! نحن على يقين من أننا
            سنقدم لك أفضل خدمة، حيث قدمنا لكثير من عملائنا أفضل النتائج. من
            المستحيل أن تصاب بخيبة أمل إذا كنت تعمل معنا.
          </p>
        </div>
        <Clients />
      </section>
      <FooterAr />
    </main>
  );
}
