import Menubar from "@/components/Menubar";
import "./globals.css";
import Head from "next/head";
// import { GoogleFont } from "@next/font/google";

// const myFont = GoogleFont({
//   family: "Poppins",
//   subsets: ["latin"], // Add more subsets if needed (e.g., ['latin', 'cyrillic'])
//   display: "swap", // Controls font loading behavior
//   variable: "--font-poppins", // Customize the variable name (optional)
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` font-Poppins `}>
      <Head>
        {/* Your other meta tags and links */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
        />{" "}
        {/* Replace with your generated link */}
      </Head>
      <body>
        <Menubar />
        {children}
      </body>
    </html>
  );
}
