// "use client";

import data from "@/app/content-en";
import Image from "next/image";
// import { usePathname, useRouter } from "next/navigation";
import React from "react";
import { redirect } from "next/navigation";
import { poppinsClass } from "@/app/font";
import { MetaData } from "next";
import Head from "next/head";

// export const generateMetaData = ({ params }): Metadata => {
//   return {
//     title: params.projectTitle,
//   };
// };
export const metadata = {
  title: "project",
  description: "Generated by create next app",
};
// async function getStaticProps({ params }) {
//   console.log("Server-side log:", params.projectId);
//   return {
//     props: {
//       projectId: params.projectId,
//     },
//   };project.title

// }
const Page = ({ params }) => {
  let exist = true;
  metadata.title = `${params.projectTitle.split("-").join(" ")}`;

  console.log("Visual-Identity-Souq-alfurat");

  let projectObj = data.projects[Number(params.projectId) - 1];
  const arrayOfStrings = params.projectTitle.split("-");

  console.log(arrayOfStrings);
  let Title = arrayOfStrings.join(" ");

  console.log(Title);
  if (!projectObj || projectObj.url != params.projectTitle) {
    exist = false;
    redirect(`/en/not-found`);
  }

  return (
    <>
      <main className={` py-[100px] ${poppinsClass}`}>
        <div className="container">
          {/* {!exist ? null : (
            // <div className=" ">
            //   product title :{params.projectId} {params.projectTitle}{" "}
            //   {`${projectObj.title}`}
            // </div>
          )} */}
          <div>
            <h1 className=" text-center leading-[118%] text-[50px] font-bold text-primaryDark">
              {projectObj.title}
            </h1>

            <div className="project-details my-10 flex justify-center gap-8">
              <div className="client flex flex-col items-center justify-center">
                <h4 className=" text-[#8A8A8A] font-medium text-[15px] text-center ">
                  CLIENT
                </h4>
                <h6 className=" text-primaryDark font-semibold text-center">
                  {projectObj.details.client}
                </h6>
              </div>
              <div className="client flex flex-col items-center ">
                <h4 className=" text-[#8A8A8A] font-medium text-[15px]">
                  SERVICES
                </h4>
                <h6 className=" text-primaryDark font-semibold text-center">
                  {projectObj.details.services}
                </h6>
              </div>
              <div className="client flex flex-col items-center">
                <h4 className=" text-[#8A8A8A] font-medium text-[15px]">
                  DURATION
                </h4>
                <h6 className=" text-primaryDark font-semibold text-center">
                  {projectObj.details.duration}
                </h6>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Page;
